version: 0.0
os: linux
files:
  - source: /
    destination: /home/Callicode_Note_App
hooks:
   ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: ec2-user
   ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ec2-user
